django/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('webtoon.urls')),
    path('admin/', admin.site.urls),
]

django/webtoon/urls.py
from django.urls import path
from . import views

app_name = 'webtoon'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:webtoon_id>/', views.episode_list, name='episode_list'),
]

django/webtoon/models.py
from django.db import models
from .crawler import Webtoon as NaverToon
from django.utils.dateparse import parse_date

import os
from config.settings import BASE_DIR


class Webtoon(models.Model):
    webtoon_no = models.IntegerField(default=0)
    title = models.CharField(max_length=200)
    thumbnail = models.CharField(max_length=300) # static 경로로 넣을것.
    author = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    url = models.CharField(max_length=100)

    def get_webtoon_info(self):
        if self.webtoon_no:
            nt = NaverToon(self.webtoon_no)
            self.webtoon_no = nt.webtoon_id
            self.title = nt.webtoon_title
            # 썸네일은 네이버에서 로딩을 막으므로 로컬에 저장한다.
            thumbnail_dir = os.path.join(os.path.join(BASE_DIR, "static"), 'webtoon_thumb')
            self.thumbnail = 'webtoon_thumb/' + nt.thumbnail_save(thumbnail_dir)[1]
            self.author = nt.webtoon_author
            self.description = nt.webtoon_description
            self.url = nt.webtoon_url
            self.save()

    def get_episode_list(self, page=1):
        nt = NaverToon(self.webtoon_no, page)
        for episode in nt.get_toons()[::-1]:
            thumbnail_dir = os.path.join(os.path.join(BASE_DIR, "static"), 'webtoon_thumb')
            thumbnail_dir = 'webtoon_thumb/' + episode.thumbnail_save(thumbnail_dir)[1]
            ep, created = Episode.objects.get_or_create(
                webtoon=self,
                webtoon_no=episode.webtoon_id,
                episode_no=episode.episode_id,
            )

            if ep.title != episode.title:
                ep.title = episode.title
            if ep.thumbnail != thumbnail_dir:
                ep.thumbnail = thumbnail_dir
            if ep.rating != episode.rating:
                ep.rating = episode.rating
            if ep.created_date != parse_date(episode.created_date.replace('.', '-')):
                ep.created_date = parse_date(episode.created_date.replace('.', '-'))
            if ep.url != episode.episode_url:
                ep.url = episode.episode_url
            ep.save()

    def __str__(self):
        return self.title


class Episode(models.Model):
    webtoon = models.ForeignKey(Webtoon, on_delete=models.CASCADE)
    webtoon_no = models.IntegerField(default=0)
    episode_no = models.IntegerField(default=0)
    title = models.CharField(max_length=200, default='')
    thumbnail = models.CharField(max_length=300) # static 경로로 넣을것.
    rating = models.CharField(max_length=4)
    created_date = models.DateField('date published', null=True)
    url = models.CharField(max_length=100)

    def __str__(self):
        return "{} - {}".format(self.webtoon, self.title)

    class Meta:
        ordering = ['-webtoon_no', '-created_date']

django/webtoon/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Webtoon, Episode

def index(request):
    """웹툰 목록을 보여준다"""
    try:
        search_webtoon = request.GET['search_webtoon']
    except Exception as e:
        search_webtoon = None

    if search_webtoon:
        toons = Webtoon.objects.filter(title__contains = search_webtoon)
    else:
        toons = Webtoon.objects.all()

    context = {
        'toons': toons,
        'search_webtoon': search_webtoon,
    }
    return render(request, 'webtoon/index.html', context)


def episode_list(request, webtoon_id):
    """웹툰의 에피소드 목록을 보여준다"""
    toon = Webtoon.objects.filter(pk=webtoon_id)
    ep = Episode.objects.filter(webtoon=webtoon_id)
    if not toon.exists() or not ep.exists():
        return redirect('webtoon:index')

    pg = Paginator(ep, 10)
    page = request.GET.get('page')
    try:
        ep_cur = pg.get_page(page)
    except PageNotAnInteger:
        ep_cur = pg.get_page(1)
    except EmptyPage:
        ep_cur = pg.get_page(pg.num_pages)

    context = {
        'webtoon': toon.get(),
        'ep': ep_cur,
    }
    return render(request, 'webtoon/episode_list.html', context)

django/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block 'doc-title' %}My Webtoon{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
            <a class="navbar-brand" href="/">Home</a>
            <form class="form-inline my-2 my-lg-0" action="{% url 'webtoon:index' %}">
                <input class="form-control mr-sm-2" name="search_webtoon" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>
        <div class="img-thumbnail my-2 p-3">
        {% block 'doc-subject' %}Subject Sample{% endblock %}
        </div>
        <div class="img-thumbnail my-2 p-0">
        {% block 'doc-body' %}{% endblock %}
        </div>
        {% block 'doc-page' %}{% endblock %}
        <div class="clearfix">&nbsp;</div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block 'doc-script' %}{% endblock %}
</body>
</html>

django/templates/webtoon/episode_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block 'doc-title' %}
    {{ block.super }}
{% endblock %}

{% block 'doc-subject' %}
    <div class="media">
        <img class="align-self-center mr-3 img-thumbnail" src="{% static webtoon.thumbnail %}" alt="Card image cap" data-adaptive-background>
        <div class="media-body">
            <h1 class="mt-0">{{ webtoon.title }}</h1>
            <h6 class="mb-2 text-muted">{{ webtoon.author }}</h6>
            {{ webtoon.description }}
        </div>
    </div>
{% endblock %}

{% block 'doc-body' %}
    <div class="table-responsive">
    <table class="table table-hover mb-0">
        <thead class="thead-light text-center">
            <tr>
                <th scope="col">이미지</th>
                <th scope="col">제목</th>
                <th scope="col">별점</th>
                <th scope="col">등록일</th>
            </tr>
        </thead>
        <tbody>
        {% for e in ep %}
            <tr>
                <td class="text-center"><img class="img-thumbnail" src="{% static e.thumbnail %}" alt="Card image cap"></td>
                <td class="align-middle">{{ e.title }} <a href="{{ e.url }}" target="_blank"><i class="fas fa-external-link-alt"></i><span class="sr-only">보러가기</span></a></td>
                <td class="text-center align-middle">{{ e.rating }}</td>
                <td class="text-center align-middle">{{ e.created_date }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

{% block 'doc-page' %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if ep.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ ep.previous_page_number }" tabindex="-1">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            {% endif %}

            {% for pg in ep.paginator.page_range %}
            <li class="page-item {%if pg == ep.number %}active{% endif %}">
                <a class="page-link" href="?page={{ pg }}">{{ pg }}</a>
            </li>
            {% endfor %}

            {% if ep.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ ep.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

{% block 'doc-script' %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.adaptive-backgrounds/1.0.3/jquery.adaptive-backgrounds.min.js"></script>
<script>
    $(document).ready(function(){
        $.adaptiveBackground.run({
            parent: 'body'
        });
    });
</script>
{% endblock %}

django/templates/webtoon/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block 'doc-title' %}
    {{ block.super }}
{% endblock %}

{% block 'doc-subject' %}
    <h1 class="display-5">웹툰 리스트</h1>
    {% if search_webtoon %}
    <div class="p-3">
        <p class="lead">'{{ search_webtoon }}' 검색 결과</p>
    </div>
    {% endif %}
{% endblock %}

{% block 'doc-body' %}
<div class="row px-3">
    {% if toons %}
        {% for toon in toons %}
        <div class="col-sm-6 col-md-4 col-lg-3 py-2">
            <div class="card">
                <img class="card-img-top" src="{% static toon.thumbnail %}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ toon.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ toon.author }}</h6>
                    <p class="card-text">{{ toon.description }}</p>
                    <a href="{% url 'webtoon:episode_list' webtoon_id=toon.pk %}" class="card-link">에피소드 보기</a>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="p-3">
            <p class="lead">웹툰 정보가 없습니다.</p>
        </div>
    {% endif %}
</div>
{% endblock %}